(function(){
  var CO='ИП Климкин Никита Сергеевич';
  var INN='971501295187';
  var OGRN='319774600227832';
  var MAIL='info@bezgranic-visa.ru';
  var D={};
  D.policy={t:'Политика конфиденциальности',h:'<p><b>1. Общие положения</b></p><p>Настоящая политика определяет порядок обработки персональных данных посетителей сайта vizovaya-akademiya.ru. Оператор — '+CO+', ИНН '+INN+', ОГРНИП '+OGRN+'.</p><p><b>2. Какие данные мы собираем</b></p><p>Имя, номер телефона, адрес электронной почты, выбранное время вебинара. Автоматически — технические данные: IP-адрес, тип браузера и устройства, файлы cookie, данные систем аналитики.</p><p><b>3. Зачем мы их обрабатываем</b></p><p>Регистрация на вебинар и напоминание о нём, отправка материалов, связь с вами, исполнение договора, информирование о продуктах и акциях, улучшение работы сайта.</p><p><b>4. Основания обработки</b></p><p>Согласие субъекта персональных данных, а также необходимость исполнения договора, стороной которого он является.</p><p><b>5. Передача третьим лицам</b></p><p>Данные могут передаваться сервисам рассылок, мессенджерам, платёжным сервисам и системам аналитики — только в объёме, необходимом для оказания услуг. Мы не продаём и не передаём данные в рекламных целях третьим лицам.</p><p><b>6. Срок хранения</b></p><p>До достижения целей обработки либо до отзыва согласия.</p><p><b>7. Ваши права</b></p><p>Вы вправе получить сведения об обработке ваших данных, требовать их уточнения, блокирования или удаления, а также отозвать согласие. Для этого напишите на '+MAIL+'. Запрос обрабатывается в течение 10 рабочих дней.</p><p><b>8. Защита данных</b></p><p>Оператор применяет организационные и технические меры для защиты данных от неправомерного доступа, уничтожения или распространения.</p><p><b>9. Изменения</b></p><p>Оператор вправе изменять политику. Актуальная редакция всегда доступна на этой странице.</p>'};
  D.offer={t:'Договор-оферта',h:'<p><b>1. Общие положения</b></p><p>Настоящий документ является публичной офертой '+CO+' (ИНН '+INN+', ОГРНИП '+OGRN+'), далее Исполнитель, о заключении договора оказания информационно-консультационных услуг.</p><p><b>2. Предмет договора</b></p><p>Исполнитель оказывает информационно-консультационные услуги в формате онлайн-обучения по программе подготовки визовых специалистов. Бесплатный вебинар предоставляется без взимания платы.</p><p><b>3. Стоимость и оплата</b></p><p>Стоимость курса «Шенгенские страны» — 60 000 рублей. НДС не облагается в связи с применением специального налогового режима. Оплата производится в размере 100% до начала оказания услуг, если иное не согласовано сторонами.</p><p><b>4. Акцепт</b></p><p>Акцептом оферты считается оплата услуг либо отправка заявки через форму на сайте. С этого момента договор считается заключённым.</p><p><b>5. Права и обязанности</b></p><p>Исполнитель обязуется предоставить доступ к материалам и сопровождение куратора. Заказчик обязуется не передавать материалы третьим лицам и не использовать их в коммерческих целях.</p>'};
  D.offer.h+='<div style="margin:18px 0;padding:16px 18px;border-radius:16px;background:rgb(232,246,244);border-left:4px solid rgb(15,118,110)"><p style="margin:0 0 8px;font-weight:800;color:rgb(15,118,110);font-size:16px">6. Возврат денежных средств</p><p style="margin:0 0 8px">Вернуть деньги можно <b>в течение 14 календарных дней с даты старта курса</b> — без объяснения причин.</p><p style="margin:0 0 8px">Заявления заполнять не нужно. Достаточно сообщить куратору.</p><p style="margin:0">Деньги возвращаются <b>в течение 24 часов</b> на те же реквизиты, с которых производилась оплата.</p></div>';
  D.offer.h+='<p><b>7. Ответственность сторон</b></p><p>Исполнитель не гарантирует конкретного уровня дохода заказчика: результат зависит от применения полученных знаний. Стороны освобождаются от ответственности при обстоятельствах непреодолимой силы.</p><p><b>8. Реквизиты Исполнителя</b></p><p>'+CO+'<br>ИНН '+INN+'<br>ОГРНИП '+OGRN+'<br>E-mail: '+MAIL+'</p>';
  D.pdn={t:'Согласие на обработку персональных данных',h:'<p>Отправляя заявку через форму на сайте, я даю согласие '+CO+' (ИНН '+INN+', ОГРНИП '+OGRN+') на обработку моих персональных данных.</p><p><b>Какие данные</b></p><p>Фамилия и имя, номер телефона, адрес электронной почты, идентификаторы в мессенджерах, технические данные о посещении сайта.</p><p><b>Какие действия разрешены</b></p><p>Сбор, запись, систематизация, хранение, уточнение, использование, передача привлечённым сервисам для исполнения договора, блокирование, удаление и уничтожение — как автоматизированно, так и без использования средств автоматизации.</p><p><b>Цели</b></p><p>Регистрация на вебинар, отправка материалов и напоминаний, связь со мной, исполнение договора, информирование о продуктах.</p><p><b>Срок действия и отзыв</b></p><p>Согласие действует до его отзыва. Отозвать его можно в любой момент письмом на '+MAIL+'. После отзыва обработка прекращается в течение 10 рабочих дней, за исключением случаев, когда хранение требуется по закону.</p>'};
  D.ads={t:'Согласие на рекламную рассылку',h:'<p>Отправляя заявку, я даю '+CO+' (ИНН '+INN+') согласие на получение информационных и рекламных сообщений в соответствии со статьёй 18 Федерального закона «О рекламе».</p><p><b>Каналы связи</b></p><p>SMS-сообщения, электронная почта, мессенджеры Telegram и MAX, а также телефонные звонки.</p><p><b>Содержание рассылки</b></p><p>Напоминания о вебинаре, полезные материалы, информация об обучающих программах, специальные предложения и акции.</p><p><b>Как отказаться</b></p><p>Отказаться от рассылки можно в любой момент: по ссылке отписки в письме, командой боту или письмом на '+MAIL+'. Отказ от рекламной рассылки не лишает доступа к оплаченным услугам и к сервисным сообщениям о вебинаре.</p>'};
  function openDoc(k){var d=D[k];if(!d)return;var ov=document.createElement('div');ov.setAttribute('data-legal','1');ov.style.cssText='position:fixed;inset:0;z-index:200;background:rgba(18,28,38,0.72);display:flex;align-items:center;justify-content:center;padding:20px';var card=document.createElement('div');card.style.cssText='background:#fff;border-radius:22px;max-width:640px;width:100%;max-height:86vh;overflow-y:auto;padding:26px 24px 28px;position:relative;box-shadow:0 40px 80px -20px rgba(20,30,45,0.5);font-size:14.5px;line-height:1.62;color:rgb(60,66,74)';var x=document.createElement('div');x.textContent='X';x.style.cssText='position:sticky;top:0;float:right;width:32px;height:32px;border-radius:50%;background:rgb(243,245,247);display:flex;align-items:center;justify-content:center;cursor:pointer;font-size:13px;color:rgb(90,96,104)';var h=document.createElement('h3');h.textContent=d.t;h.style.cssText='margin:0 0 14px;font-family:Nunito,sans-serif;font-weight:900;font-size:21px;color:rgb(25,32,40);padding-right:40px';var body=document.createElement('div');body.innerHTML=d.h;card.appendChild(x);card.appendChild(h);card.appendChild(body);ov.appendChild(card);document.body.appendChild(ov);function close(){if(ov.parentNode)ov.parentNode.removeChild(ov)}x.addEventListener('click',close);ov.addEventListener('click',function(e){if(e.target===ov)close()})}
  function lk(k,txt){return '<a href="#" data-doc="'+k+'" style="color:inherit;text-decoration:underline;text-underline-offset:2px;cursor:pointer">'+txt+'</a>'}
  var CONSENT='Нажимая «Записаться», я принимаю '+lk('offer','договор-оферту')+', соглашаюсь с '+lk('policy','политикой конфиденциальности')+', даю согласие на '+lk('pdn','обработку персональных данных')+' и на получение '+lk('ads','информационных и рекламных сообщений')+' по SMS, e-mail и в мессенджерах.';
  function footer(){if(document.getElementById('lgFooter'))return;var host=document.querySelector('x-dc')||document.body;var f=document.createElement('footer');f.id='lgFooter';f.style.cssText='background:rgb(247,248,249);border-top:1px solid rgb(228,232,236);padding:34px 6vw 30px;font-size:13px;line-height:1.7;color:rgb(108,115,124);text-align:center';var name=document.createElement('div');name.textContent=CO;name.style.cssText='font-weight:800;color:rgb(52,58,66);font-size:14px;margin-bottom:4px';var req=document.createElement('div');req.textContent='ИНН '+INN+' · ОГРНИП '+OGRN;req.style.cssText='margin-bottom:16px';var links=document.createElement('div');links.style.cssText='display:flex;flex-wrap:wrap;gap:8px 18px;justify-content:center;margin-bottom:18px';var keys=[['policy','Политика конфиденциальности'],['offer','Договор-оферта'],['pdn','Согласие на обработку персональных данных'],['ads','Согласие на рекламную рассылку']];for(var i=0;i<keys.length;i++){var a=document.createElement('a');a.href='#';a.setAttribute('data-doc',keys[i][0]);a.textContent=keys[i][1];a.style.cssText='color:rgb(15,118,110);text-decoration:none;border-bottom:1px solid rgba(15,118,110,0.35);padding-bottom:1px';links.appendChild(a)}var cp=document.createElement('div');cp.textContent='© 2026 Визовая академия. Все права защищены.';cp.style.cssText='color:rgb(140,147,156);font-size:12.5px';f.appendChild(name);f.appendChild(req);f.appendChild(links);f.appendChild(cp);host.appendChild(f)}
  function consent(){var all=document.querySelectorAll('div,p,span');for(var i=0;i<all.length;i++){var e=all[i];if(e.children.length)continue;var t=(e.textContent||'').trim();if(t.indexOf('Нажимая «Записаться»')===0){e.innerHTML=CONSENT}}}
  function run(){footer();consent()}
  document.addEventListener('click',function(e){var a=e.target.closest?e.target.closest('[data-doc]'):null;if(a){e.preventDefault();openDoc(a.getAttribute('data-doc'))}});
  if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',function(){run();setInterval(run,900)})}else{run();setInterval(run,900)}
})();
